Vagrant.configure("2") do |config|
    
    #Definir le nom de la machine dans vagrant. Replace default
    config.vm.define "formation-docker"
    
    #Definir le provider 
    config.vm.provider "virtualbox" do |v|
        #Definir le nom de la VM dans le provider en remplacement de celui par defaut
        v.name = "formation-docker"
    end

    #Definir le hostname de la V
    config.vm.hostname = "formation-docker"
    
    config.vm.box = "hashicorp/bionic64"

end